workflows:
  ios-workflow:
    name: Build iOS IPA
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --release
    ios:
      code_signing:
        use_codemagic_generated: true
    artifacts:
      - build/ios/ipa/*.ipa
    triggering:
      events:
        - push
