workflows:
  ios-workflow:
    name: Build iOS Simulator App
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS simulator app
        script: |
          flutter build ios --simulator --release
      - name: Zip Runner.app
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.zip Runner.app
    artifacts:
      - build/ios/iphonesimulator/Runner.zip
    triggering:
      events:
        - push
