workflows:
  ios-release-workflow:
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS for simulator
        script: |
          flutter build ios --simulator
    artifacts:
      - build/ios/iphonesimulator/*.app
