workflows:
  ios_demo_build:
    name: iOS Unsigned IPA (for sharing)
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build iOS (unsigned)
        script: |
          flutter build ios --release --no-codesign
      - name: Package .ipa manually
        script: |
          cd build/ios/iphoneos
          rm -rf Payload
          mkdir Payload
          # If your app folder isn't Runner.app, replace the name below
          cp -R "Runner.app" Payload/
          # Create demo.ipa
          zip -r demo.ipa Payload
    artifacts:
      - build/ios/iphoneos/demo.ipa
