workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build iOS simulator app
        script: flutter build ios --simulator --release
      - name: Zip Runner.app
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.zip Runner.app
    artifacts:
      - build/ios/iphonesimulator/Runner.zip
